const calls = [
    { method: 'GET', 
        path: '/',
        params: [],
        action: 'getStats' },
    { method: 'GET',
        path: '/@$1',
        params: ['id'],
        action: 'getAccount' },
    { method: 'GET',
        path: '/user_services/$1',
        params: ['id'],
        action: 'getServicesByUser' },
    { method: 'GET',
        path: '/services/$1',
        params: ['type'],
        action: 'getServicesByType' },
    { method: 'GET',
        path: '/api/mirrors',
        params: [],
        action: 'getMirrors' },
    { method: 'GET',
        path: '/api/coin_detail',
        params: [],
        action: 'getCoinDetail' },
    { method: 'GET',
        path: '/report/$1',
        params: ['id'],
        action: 'getNodeReport' },
    { method: 'GET',
        path: '/markets',
        params: [],
        action: 'getNodes' },
    { method: 'GET',
        path: '/feed',
        params: [],
        action: 'getFeed' },
    { method: 'GET',
        path: '/runners',
        params: [],
        action: 'getRunners' },
    { method: 'GET',
        path: '/queue',
        params: [],
        action: 'getQueue' },
    { method: 'GET',
        path: '/api/protocol',
        params: [],
        action: 'getProtocol' },
    { method: 'GET',
        path: '/api/status/$1',
        params: ['txid'],
        action: 'getTxStatus' },
    { method: 'GET',
        path: '/api/contract/$1/$2/$3',
        params: ['to', 'from', 'id'],
        action: 'getChannel' },
    { method: 'GET',
        path: '/api/fileContract/$1',
        params: ['id'],
        action: 'getFileContract' },
    { method: 'GET',
        path: '/api/file/$1',
        params: ['cid'],
        action: 'getContractByFile' },
    { method: 'GET',
        path: '/dex',
        params: [],
        action: 'getDex' },
    { method: 'GET',
        path: '/api/tickers',
        params: [],
        action: 'getTickers' },
    { method: 'GET',
        path: '/api/orderbook',
        params: [],
        action: 'getOrderbook' },
    { method: 'GET',
        path: '/api/pairs',
        params: [],
        action: 'getPairs' },
    { method: 'GET',
        path: '/api/orderbook/$1',
        params: ['pair'],
        action: 'getOrderbookByPair' },
    { method: 'GET',
        path: '/api/historical',
        params: [],
        action: 'getDexHistory' },
    { method: 'GET',
        path: '/api/historical/$1',
        params: ['pair'],
        action: 'getDexHistoryByPair' },
    { method: 'GET',
        path: '/api/recent/$1',
        params: ['pair'],
        action: 'getRecentTrades' }
]

export { calls }